"""add FinetuneJob ORM model

Revision ID: 225d7b006ab3
Revises: 431bcaa8bd54
Create Date: 2026-08-20 16:35:58.424940

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '225d7b006ab3'
down_revision: str | Sequence[str] | None = '431bcaa8bd54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
