"""baseline from ORM

Revision ID: 431bcaa8bd54
Revises: 
Create Date: 2026-08-20 16:34:20.996141

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '431bcaa8bd54'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # P2-05 baseline：清理 ORM 未映射的遗留空表（已验证全部 0 行，无数据损失；
    # 用 CASCADE 规避表间外键依赖顺序问题）。
    _LEGACY_EMPTY_TABLES = [
        "user_wechat_bindings", "question_templates", "api_cost_stats",
        "voice_segments", "event_tags", "tags", "profile_sensitive",
        "sensitive_words", "app_settings", "guardrail_logs", "question_history",
        "audit_log", "profile_l2_evidence", "geo_cache", "content_tags",
        "ai_request_logs",
    ]
    for t in _LEGACY_EMPTY_TABLES:
        op.execute(f'DROP TABLE IF EXISTS "{t}" CASCADE')
    op.alter_column('contents', 'content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('contents', 'content_class',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'class_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'model_version',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'place',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'perceptual_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'sensitive_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'正常'::text"))
    op.alter_column('contents', 'qdrant_text_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'qdrant_image_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'cos_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'thumbnail_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contents', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('contents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::text"))
    op.drop_index(op.f('idx_contents_taken_at'), table_name='contents')
    op.drop_index(op.f('idx_contents_user_created'), table_name='contents')
    op.drop_index(op.f('idx_contents_user_type'), table_name='contents')
    op.create_index(op.f('ix_contents_user_id'), 'contents', ['user_id'], unique=False)
    op.drop_constraint(op.f('contents_user_id_fkey'), 'contents', type_='foreignkey')
    op.alter_column('correction_log', 'content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.alter_column('correction_log', 'qdrant_point_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('correction_log', 'old_label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('correction_log', 'new_label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('correction_log', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('idx_correction_log_user'), table_name='correction_log')
    op.create_index(op.f('ix_correction_log_user_id'), 'correction_log', ['user_id'], unique=False)
    op.drop_constraint(op.f('correction_log_content_id_fkey'), 'correction_log', type_='foreignkey')
    op.drop_constraint(op.f('correction_log_user_id_fkey'), 'correction_log', type_='foreignkey')
    op.alter_column('deleted_logs', 'cleanup_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('devices', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('devices', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('devices', 'refresh_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('devices_user_id_device_id_key1'), 'devices', type_='unique')
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_unique_constraint('uq_devices_user_device', 'devices', ['user_id', 'device_id'])
    op.drop_constraint(op.f('devices_user_id_fkey1'), 'devices', type_='foreignkey')
    op.alter_column('echo_history', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('echo_history', 'fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('echo_history_user_id_event_id_key'), 'echo_history', type_='unique')
    op.create_index(op.f('ix_echo_history_user_id'), 'echo_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('echo_history_user_id_fkey'), 'echo_history', type_='foreignkey')
    op.drop_constraint(op.f('echo_history_event_id_fkey'), 'echo_history', type_='foreignkey')
    op.alter_column('event_edit_log', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('event_edit_log_event_id_fkey'), 'event_edit_log', type_='foreignkey')
    op.drop_constraint(op.f('event_edit_log_user_id_fkey'), 'event_edit_log', type_='foreignkey')
    op.drop_index(op.f('idx_event_items_event'), table_name='event_items')
    op.drop_constraint(op.f('event_items_content_id_fkey'), 'event_items', type_='foreignkey')
    op.drop_constraint(op.f('event_items_event_id_fkey'), 'event_items', type_='foreignkey')
    op.alter_column('events', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'title_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'place',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'sensitivity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('events', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('events', 'generated_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('idx_events_user_level'), table_name='events')
    op.drop_index(op.f('idx_events_user_start'), table_name='events')
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.drop_constraint(op.f('events_parent_event_id_fkey'), 'events', type_='foreignkey')
    op.drop_constraint(op.f('events_user_id_fkey'), 'events', type_='foreignkey')
    op.alter_column('messages', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'in_app'::text"))
    op.alter_column('messages', 'msg_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('messages', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'unread'::text"))
    op.drop_index(op.f('idx_messages_user_sent'), table_name='messages')
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.alter_column('offline_queue', 'op_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('offline_queue', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('offline_queue', 'op_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('offline_queue', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.create_index(op.f('ix_offline_queue_user_id'), 'offline_queue', ['user_id'], unique=False)
    op.drop_constraint(op.f('offline_queue_user_id_fkey'), 'offline_queue', type_='foreignkey')
    op.alter_column('profile_dimension_history', 'dimension',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profile_dimension_history', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_pdh_user_dim'), table_name='profile_dimension_history')
    op.create_index(op.f('ix_profile_dimension_history_user_id'), 'profile_dimension_history', ['user_id'], unique=False)
    op.drop_constraint(op.f('profile_dimension_history_user_id_fkey'), 'profile_dimension_history', type_='foreignkey')
    op.alter_column('profile_dimension_pending', 'dimension',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profile_dimension_pending', 'raw_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profile_dimension_pending', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('profile_dimension_pending', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.create_index(op.f('ix_profile_dimension_pending_user_id'), 'profile_dimension_pending', ['user_id'], unique=False)
    op.drop_constraint(op.f('profile_dimension_pending_user_id_fkey'), 'profile_dimension_pending', type_='foreignkey')
    op.alter_column('sms_codes', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sms_codes', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_sms_codes_phone_created'), table_name='sms_codes')
    op.create_index(op.f('ix_sms_codes_phone'), 'sms_codes', ['phone'], unique=False)
    op.alter_column('sync_field_versions', 'entity_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('sync_field_versions', 'field',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_sync_fv_entity'), table_name='sync_field_versions')
    op.drop_index(op.f('idx_sync_fv_user'), table_name='sync_field_versions')
    op.create_index(op.f('ix_sync_field_versions_user_id'), 'sync_field_versions', ['user_id'], unique=False)
    op.alter_column('sync_state', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('sync_state_user_id_device_id_key'), 'sync_state', type_='unique')
    op.create_index(op.f('ix_sync_state_user_id'), 'sync_state', ['user_id'], unique=False)
    op.drop_constraint(op.f('sync_state_user_id_fkey'), 'sync_state', type_='foreignkey')
    op.drop_index(op.f('idx_user_profile_dimensions'), table_name='user_profile', postgresql_using='gin')
    op.drop_constraint(op.f('user_profile_user_id_fkey'), 'user_profile', type_='foreignkey')
    op.alter_column('users', 'unionid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('wechat_messages', 'msg_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('wechat_messages', 'msg_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('wechat_messages', 'media_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('wechat_messages', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::text"))
    op.drop_constraint(op.f('wechat_messages_user_id_fkey'), 'wechat_messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('wechat_messages_user_id_fkey'), 'wechat_messages', 'users', ['user_id'], ['id'])
    op.alter_column('wechat_messages', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::text"))
    op.alter_column('wechat_messages', 'media_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('wechat_messages', 'msg_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wechat_messages', 'msg_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'avatar',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'unionid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('user_profile_user_id_fkey'), 'user_profile', 'users', ['user_id'], ['id'])
    op.create_index(op.f('idx_user_profile_dimensions'), 'user_profile', ['dimensions'], unique=False, postgresql_using='gin')
    op.create_foreign_key(op.f('sync_state_user_id_fkey'), 'sync_state', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_sync_state_user_id'), table_name='sync_state')
    op.create_unique_constraint(op.f('sync_state_user_id_device_id_key'), 'sync_state', ['user_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('sync_state', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sync_field_versions_user_id'), table_name='sync_field_versions')
    op.create_index(op.f('idx_sync_fv_user'), 'sync_field_versions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sync_fv_entity'), 'sync_field_versions', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('sync_field_versions', 'field',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sync_field_versions', 'entity_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sms_codes_phone'), table_name='sms_codes')
    op.create_index(op.f('idx_sms_codes_phone_created'), 'sms_codes', ['phone', 'created_at'], unique=False)
    op.alter_column('sms_codes', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sms_codes', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('profile_dimension_pending_user_id_fkey'), 'profile_dimension_pending', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_profile_dimension_pending_user_id'), table_name='profile_dimension_pending')
    op.alter_column('profile_dimension_pending', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('profile_dimension_pending', 'count',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('profile_dimension_pending', 'raw_answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('profile_dimension_pending', 'dimension',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('profile_dimension_history_user_id_fkey'), 'profile_dimension_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_profile_dimension_history_user_id'), table_name='profile_dimension_history')
    op.create_index(op.f('idx_pdh_user_dim'), 'profile_dimension_history', ['user_id', 'dimension', 'updated_at'], unique=False)
    op.alter_column('profile_dimension_history', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('profile_dimension_history', 'dimension',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('offline_queue_user_id_fkey'), 'offline_queue', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_offline_queue_user_id'), table_name='offline_queue')
    op.alter_column('offline_queue', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('offline_queue', 'op_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('offline_queue', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('offline_queue', 'op_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.create_index(op.f('idx_messages_user_sent'), 'messages', ['user_id', sa.literal_column('sent_at DESC')], unique=False)
    op.alter_column('messages', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'unread'::text"))
    op.alter_column('messages', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'msg_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'channel',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'in_app'::text"))
    op.create_foreign_key(op.f('events_user_id_fkey'), 'events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('events_parent_event_id_fkey'), 'events', 'events', ['parent_event_id'], ['id'])
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.create_index(op.f('idx_events_user_start'), 'events', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('idx_events_user_level'), 'events', ['user_id', 'level'], unique=False)
    op.alter_column('events', 'generated_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('events', 'sensitivity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'place',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'title_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('events', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('event_items_event_id_fkey'), 'event_items', 'events', ['event_id'], ['id'])
    op.create_foreign_key(op.f('event_items_content_id_fkey'), 'event_items', 'contents', ['content_id'], ['id'])
    op.create_index(op.f('idx_event_items_event'), 'event_items', ['event_id'], unique=False)
    op.create_foreign_key(op.f('event_edit_log_user_id_fkey'), 'event_edit_log', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('event_edit_log_event_id_fkey'), 'event_edit_log', 'events', ['event_id'], ['id'])
    op.alter_column('event_edit_log', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key(op.f('echo_history_event_id_fkey'), 'echo_history', 'events', ['event_id'], ['id'])
    op.create_foreign_key(op.f('echo_history_user_id_fkey'), 'echo_history', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_echo_history_user_id'), table_name='echo_history')
    op.create_unique_constraint(op.f('echo_history_user_id_event_id_key'), 'echo_history', ['user_id', 'event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('echo_history', 'fingerprint',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('echo_history', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('devices_user_id_fkey1'), 'devices', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_devices_user_device', 'devices', type_='unique')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.create_unique_constraint(op.f('devices_user_id_device_id_key1'), 'devices', ['user_id', 'device_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('devices', 'refresh_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('devices', 'platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'device_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('deleted_logs', 'cleanup_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.create_foreign_key(op.f('correction_log_user_id_fkey'), 'correction_log', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('correction_log_content_id_fkey'), 'correction_log', 'contents', ['content_id'], ['id'])
    op.drop_index(op.f('ix_correction_log_user_id'), table_name='correction_log')
    op.create_index(op.f('idx_correction_log_user'), 'correction_log', ['user_id', 'created_at'], unique=False)
    op.alter_column('correction_log', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('correction_log', 'new_label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('correction_log', 'old_label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('correction_log', 'qdrant_point_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('correction_log', 'content_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.create_foreign_key(op.f('contents_user_id_fkey'), 'contents', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_contents_user_id'), table_name='contents')
    op.create_index(op.f('idx_contents_user_type'), 'contents', ['user_id', 'content_type'], unique=False)
    op.create_index(op.f('idx_contents_user_created'), 'contents', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_contents_taken_at'), 'contents', ['user_id', 'taken_at'], unique=False)
    op.alter_column('contents', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'processing'::text"))
    op.alter_column('contents', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('contents', 'thumbnail_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'cos_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'qdrant_image_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'qdrant_text_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'sensitive_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'正常'::text"))
    op.alter_column('contents', 'perceptual_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'place',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'model_version',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'class_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'content_class',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contents', 'content_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('ai_request_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engine', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('calls', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('cost_est', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'done'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_request_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_request_logs_pkey'))
    )
    op.create_index(op.f('idx_ai_logs_provider_date'), 'ai_request_logs', ['provider', 'created_at'], unique=False)
    op.create_table('content_tags',
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('content_tags_content_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('content_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('content_id', 'tag_id', name=op.f('content_tags_pkey'))
    )
    op.create_index(op.f('idx_content_tags_tag'), 'content_tags', ['tag_id'], unique=False)
    op.create_table('geo_cache',
    sa.Column('geohash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('geohash', name=op.f('geo_cache_pkey'))
    )
    op.create_table('profile_l2_evidence',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dimension', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evidence_content_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('profile_l2_evidence_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_l2_evidence_pkey'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_log_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('idx_audit_log_user'), 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('question_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fingerprint', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('asked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('send_status', sa.TEXT(), server_default=sa.text("'sent'::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('question_history_content_id_fkey')),
    sa.ForeignKeyConstraint(['template_id'], ['question_templates.id'], name=op.f('question_history_template_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('question_history_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_history_pkey')),
    sa.UniqueConstraint('user_id', 'fingerprint', name=op.f('question_history_user_id_fingerprint_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('guardrail_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('engine', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('cost_tokens', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('guardrail_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('guardrail_logs_pkey'))
    )
    op.create_table('app_settings',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ai_engine', sa.TEXT(), server_default=sa.text("'cloud'::text"), autoincrement=False, nullable=False),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('cross_device_visible', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('import_sessions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('app_settings_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('app_settings_pkey'))
    )
    op.create_table('sensitive_words',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False, comment='三层词表来源：1=预置基础词表 2=画像敏感标记驱动 3=违规词回流（v3 F1）'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sensitive_words_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensitive_words_pkey')),
    sa.UniqueConstraint('word', 'user_id', name=op.f('sensitive_words_word_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('profile_sensitive',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('topic_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('profile_sensitive_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_sensitive_pkey')),
    sa.UniqueConstraint('user_id', 'topic', name=op.f('profile_sensitive_user_id_topic_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tags',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.TEXT(), server_default=sa.text("'custom'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tags_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey')),
    sa.UniqueConstraint('user_id', 'name', name=op.f('tags_user_id_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('finetune_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dataset_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('finetune_jobs_pkey'))
    )
    op.create_table('event_tags',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_tags_event_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('event_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', 'tag_id', name=op.f('event_tags_pkey')),
    comment='事件标签多对多（v3：替代 events.tags JSONB）'
    )
    op.create_table('voice_segments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('seg_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('end_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('segment_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('segment_emotion', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name=op.f('voice_segments_content_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('voice_segments_pkey')),
    sa.UniqueConstraint('content_id', 'seg_no', name=op.f('voice_segments_content_id_seg_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('api_cost_stats',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stat_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_calls', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('api_cost_stats_pkey')),
    sa.UniqueConstraint('provider', 'stat_date', name=op.f('api_cost_stats_provider_stat_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('question_templates',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('template_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slot_vars', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('question_templates_pkey'))
    )
    op.create_table('user_wechat_bindings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('openid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bound_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_wechat_bindings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_wechat_bindings_pkey')),
    sa.UniqueConstraint('openid', name=op.f('user_wechat_bindings_openid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
